export const GET_DATA = "GET_DATA";
export const GET_COUNTRIES = "GET_COUNTRIES";
export const GET_DATA_BY_COUNTRY = "GET_DATA_BY_COUNTRY";
export const REMOVE_DATA_SELECTED = "REMOVE_DATA_SELECTED";

export const GET_DATA_BY_HISTORY = "GET_DATA_BY_HISTORY";
export const GET_DATA_BY_HISTORY_AND_COUNTRY =
  "GET_DATA_BY_HISTORY_AND_COUNTRY";
export const REMOVE_DATA_BY_HISTORY = "REMOVE_DATA_BY_HISTORY";

export const GET_VACCINE_BY_HISTORY = "GET_VACCINE_BY_HISTORY";
export const GET_VACCINE_BY_HISTORY_AND_COUNTRY =
  "GET_VACCINE_BY_HISTORY_AND_COUNTRY";
export const REMOVE_VACCINE_BY_HISTORY = "REMOVE_VACCINE_BY_HISTORY";

export const GET_NEWS = "GET_NEWS";
export const GET_PERPAGE_NEWS = "GET_PERPAGE_NEWS";
export const REMOVE_NEWS = "REMOVE_NEWS";
